### ISSUE TITLE
project doesn't build

### ISSUE THREAD

**Issue by XenGi** [uwekamper/YeahLetsAndroidThat#1]
One of the dependencies still uses the `android` command which is deprecated and removed from the sdk for half a year now.

**Comment by ligi** [comment]
?
```
:app:build

BUILD SUCCESSFUL

Total time: 7 mins 44.285 secs
⋊> ~/t/YeahLetsAndroidThat on master ◦ git rev-parse HEAD                                                                                                               19:48:08
f80faec4b7cd19736960cf4bad6c4de80f36ae7b
```

from `./gradlew clean build` on latest head

**Comment by XenGi** [comment]
Android studio updated everything. I think what caused the error was the update to gradle v3. I did a clean checkout and now it builds.

But I can't install the package. Phone says it is corrupt. I tried the release version.

I can install the debug version but it crashes when I click on a campaign.
